# Generated by Django 4.1.2 on 2022-10-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_detail', to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_detail', to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(),
        ),
    ]
